version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    # Commenting out the volume mount to use the built version
    # volumes:
    #   # mount local application directory to /app instead of nested path
    #   - ./my-app:/app:ro